### ISSUE TITLE
Preserve backwards compatibility for GalaxyIndex

### ISSUE THREAD

**Issue by manodeep** [sage-home/sage-model#12]
https://github.com/sage-home/sage-model/blob/36b2412c30542707ead788f47975f27ac776958f/src/core_save.c#L113

`ThisTask` should be `filenr` to preserve backwards compatibility with old-sage

**Comment by jacobseiler** [comment]
This has been fixed and checked with the [old version](https://github.com/darrencroton/sage) of SAGE.  Mini-Millennium produces identical values for `GalaxyIndex` and `CentralGalaxyIndex`.
