### ISSUE TITLE
Curl not able to download mini-millennium files

### ISSUE THREAD

**Issue by aussing** [sage-home/sage-model#29]
Using version curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5 was not able to download the mini-millenium tree files from dropbox

**Comment by darrencroton** [comment]
@manodeep, could you have a look on Monday?

**Comment by manodeep** [comment]
@darrencroton This is already sorted for @aussing but noting here so that we are aware that such an issue might exist

**Comment by darrencroton** [comment]
Thanks @manodeep!

**Comment by aussing** [comment]
Screenshot of the error message I got after running first_run.sh

![Screen Shot 2021-03-31 at 3 52 11 PM (1)](https://user-images.githubusercontent.com/82134604/113974105-b54eac80-9880-11eb-9f71-6add58ab5cfc.png)

**Comment by darrencroton** [comment]
This seems to work now so closing
