### ISSUE TITLE
Could not write the dataset for the Type field for output snapshot 39

### ISSUE THREAD

**Issue by aporrasval** [sage-home/sage-model#42]
I followed the steps to run the mini-millennium trees in SAGE from https://github.com/sage-home/sage-model and I get this error after running mpirun -np <NUMBER_PROCESSORS> ./sage input/millennium.par

Note: HDF5 is already installed

```
.HDF5-DIAG: Error detected in HDF5 (1.8.17) thread 139794767771456:
  #000: H5Dio.c line 271 in H5Dwrite(): can't prepare for writing data
    major: Dataset
    minor: Write failed
  #001: H5Dio.c line 352 in H5D__pre_write(): can't write data
    major: Dataset
    minor: Write failed
  #002: H5Dio.c line 795 in H5D__write(): can't write data
    major: Dataset
    minor: Write failed
  #003: H5Dchunk.c line 1985 in H5D__chunk_write(): error looking up chunk address
    major: Dataset
    minor: Can't get value
  #004: H5Dchunk.c line 2441 in H5D__chunk_lookup(): can't query chunk address
    major: Dataset
    minor: Can't get value
  #005: H5Dbtree.c line 998 in H5D__btree_idx_get_addr(): can't get chunk info
    major: Dataset
    minor: Can't get value
  #006: H5B.c line 340 in H5B_find(): unable to load B-tree node
    major: B-Tree node
    minor: Unable to protect metadata
  #007: H5AC.c line 1262 in H5AC_protect(): H5C_protect() failed.
    major: Object cache
    minor: Unable to protect metadata
  #008: H5C.c line 3574 in H5C_protect(): can't load entry
    major: Object cache
    minor: Unable to load metadata into cache
  #009: H5C.c line 7954 in H5C_load_entry(): unable to load entry
    major: Object cache
    minor: Unable to load metadata into cache
  #010: H5Bcache.c line 136 in H5B__load(): can't read B-tree node
    major: B-Tree node
    minor: Read failed
  #011: H5Fio.c line 120 in H5F_block_read(): read through metadata accumulator failed
    major: Low-level I/O
    minor: Read failed
  #012: H5Faccum.c line 214 in H5F__accum_read(): driver read request failed
    major: Low-level I/O
    minor: Read failed
  #013: H5FDint.c line 207 in H5FD_read(): addr overflow, addr = 8369400, size=2096, eoa=8369400
    major: Invalid arguments to routine
    minor: Address overflowed
Could not write the dataset for the Type field for output snapshot 39.
The dataset ID value is 83886080.
The old dimensions were 0 and we attempting to extend (and write to) this by 8192 elements.
The HDF5 datatype was #h5_dtype.
```
(*MS* formatting edit to prevent/remove spurious links to issues)

**Comment by aporrasval** [comment]
This issue was also present about a year ago and was brought up in issue #38. Some fix was done to solve it, but currently, it isn't working anymore. I am using the latest version of SAGE and have the lastest hdf5.

**Comment by manodeep** [comment]
Thanks @aporrasval - looks like #38 is still open. Some other related issue has been resolved. I will have to check and report back. 

After getting the latest version of sage-model, and updating the paramers related to file-paths and outputs, did you make any other changes to run on the TNG-100 hdf5 files?

**Comment by aporrasval** [comment]
Not in the sage-model code. To trouble shoot, I added the following in my .bash_profile thinking it could have been a path issue relating to HDF5: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/anaconda3/pkgs/hdf5-1.10.4-hb1b8bf9_0/lib

however, things don't work yet.

**Comment by manodeep** [comment]
Hold on - just realised that you are running on mini-millennium trees and generating hdf5 output. That should run just fine - those are part of the test suite (which all seem to have passed).

**Comment by aporrasval** [comment]
Yes, but I do get this error when I set the OutputFormat = sage_hdf5

I don't know if that was tested.

**Comment by manodeep** [comment]
Yup both the output formats are tested. `sage` is run twice - first time to create the binary output and the second time to create a hdf5 output

Just to confirm that the tests do pass on the current version, I created a new pull request and the tests are passing.

**Comment by manodeep** [comment]
@aporrasval I am closing this issue. Please feel free to re-open the issue if you are still having trouble
