### ISSUE TITLE
Unit conversion for spin issue

### ISSUE THREAD

**Issue by arhstevens** [sage-home/sage-model#46]
Presently assumed the unit conversion for halo spin (specific angular momentum) for lhalotree hdf5->binary is (kpc/h)(km/s)->Mpc*km/s, but it is actually ->(Mpc/h)(km/s).  No need to apply a factor of h.

https://github.com/sage-home/sage-model/blob/9d7fcfa4d3d82923c3d0906b8f8bb63cd30d122e/src/io/read_tree_lhalo_hdf5.c#L421

**Comment by darrencroton** [comment]
Damn you little h!

**Comment by manodeep** [comment]
@darrencroton and I walked through the code last week and @arhstevens you are totally right! We need to remove the extra `h` scaling from that line.

Related: @darrencroton We should also remove the `Pos` scaling by 0.001 to convert from `kpc -> Mpc` - that needs to be accounted for by changing the Units in the parameter file. Does that seem reasonable?
