### ISSUE TITLE
Duplicate LICENSE file

### ISSUE THREAD

**Issue by manodeep** [sage-home/sage-model#5]
There is a `LICENSE` file as well as a `LICENSE.txt` file. We will want to keep only one of these

**Comment by manodeep** [comment]
The content looks very similar, possibly identical. The only difference is that the copyright owner has now changed from (2015) Darren Croton to (2019) SAGE.

**Comment by jacobseiler** [comment]
A `vimdiff` shows the only notable difference between the copyright owner.  Should we keep it as (2019) SAGE or update to (2015) Darren Croton?

**Comment by manodeep** [comment]
This has been fixed on the `master` branch
